In [6]:
import pandas as pd

In [7]:
df=pd.read_excel('Heart.xlsx')

In [8]:
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [9]:
df.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [10]:
df.dtypes

Unnamed: 0      int64
Age             int64
Sex             int64
ChestPain      object
RestBP          int64
Chol            int64
Fbs             int64
RestECG         int64
MaxHR           int64
ExAng           int64
Oldpeak       float64
Slope           int64
Ca            float64
Thal           object
AHD            object
dtype: object

In [ ]:
df= df.drop(['cp'],axis =1)

In [12]:
df['Oldpeak'] = df['Oldpeak'].astype(int)

In [13]:
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0,1,NaN,normal,No

In [14]:
df.dtypes

Unnamed: 0      int64
Age             int64
Sex             int64
ChestPain      object
RestBP          int64
Chol            int64
Fbs             int64
RestECG         int64
MaxHR           int64
ExAng           int64
Oldpeak         int32
Slope           int64
Ca            float64
Thal           object
AHD            object
dtype: object

In [19]:
df.tail()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
298,299,45,1,typical,110,264,0,0,132,0,1,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0,1,NaN,normal,No

In [ ]:
df.shape

In [ ]:
df =df.fillna(df.mean())
df

In [ ]:
df=df.drop_duplicates()

In [20]:
countFemale = len(df[df.Sex == 0])
countMale = len(df[df.Sex == 1])
print("Percentage of Female Patients: {}%".format((countFemale / (len(df.Sex))*100)))
print("Percentage of Male Patients: {}%".format((countMale / (len(df.Sex))*100)))

Percentage of Female Patients: 32.01320132013201%
Percentage of Male Patients: 67.98679867986799%

In [25]:
countNoDisease = len(df[df.AHD == 'Yes'])
countHaveDisease = len(df[df.AHD == 'No'])
print("Percentage of Patients Haven't Heart Disease: {:.2f}%".format((countNoDisease / (len(df.AHD))*100)))
print("Percentage of Patients Have Heart Disease: {:.2f}%".format((countHaveDisease / (len(df.AHD))*100)))

Percentage of Patients Haven't Heart Disease: 45.87%
Percentage of Patients Have Heart Disease: 54.13%

In [28]:
df.groupby('Sex').mean()

C:\Users\Sameer\AppData\Local\Temp\ipykernel_17676\3123540612.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Sex').mean()

,Unnamed: 0,Age,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca
Sex,,,,,,,,,,,
0,161.030928,55.721649,133.340206,261.752577,0.123711,0.958763,151.226804,0.226804,0.618557,1.567010,0.546392
1,147.747573,53.834951,130.912621,239.601942,0.160194,1.004854,148.844660,0.373786,0.834951,1.616505,0.732673

In [30]:
summary_df = df['Age'].agg(['mean', 'std', 'min', 'max'])

In [34]:
summary_df

mean    54.438944
std      9.038662
min     29.000000
max     77.000000
Name: Age, dtype: float64

In [39]:
a = pd.get_dummies(df['Ca'], prefix = "ca")
b = pd.get_dummies(df['Thal'], prefix = "thal")
c = pd.get_dummies(df['Slope'], prefix = "slope")

In [45]:
frames = [df, a, b, c]
df = pd.concat(frames, axis = 1)
df.head()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,...,ca_0.0,ca_1.0,ca_2.0,ca_3.0,thal_fixed,thal_normal,thal_reversable,slope_1,slope_2,slope_3
0,1,63,1,typical,145,233,1,2,150,0,...,1,0,0,0,1,0,0,0,0,1
1,2,67,1,asymptomatic,160,286,0,2,108,1,...,0,0,0,1,0,1,0,0,1,0
2,3,67,1,asymptomatic,120,229,0,2,129,1,...,0,0,1,0,0,0,1,0,1,0
3,4,37,1,nonanginal,130,250,0,0,187,0,...,1,0,0,0,0,1,0,0,0,1
4,5,41,0,nontypical,130,204,0,2,172,0,...,1,0,0,0,0,1,0,1,0,0

In [44]:
df = df.drop(columns = ['cp', 'thal', 'slope'])
df.head()

KeyError: "['cp' 'thal' 'slope'] not found in axis"

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
x = df[['trestbps','thalach']]
y = df['target']

In [41]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

c:\python 39\lib\site-packages\numpy\core\fromnumeric.py:84: FutureWarning: In a future version, DataFrame.min(axis=None) will return a scalar min over the entire DataFrame. To retain the old behavior, use 'frame.min(axis=0)' or just 'frame.min()'
  return reduction(axis=axis, out=out, **passkwargs)
c:\python 39\lib\site-packages\numpy\core\fromnumeric.py:84: FutureWarning: In a future version, DataFrame.max(axis=None) will return a scalar max over the entire DataFrame. To retain the old behavior, use 'frame.max(axis=0)' or just 'frame.max()'
  return reduction(axis=axis, out=out, **passkwargs)

In [42]:
model1 = LinearRegression()
model1.fit(x_train, y_train)

In [43]:
predictions = model1.predict(x_test)

Accuracy: 0.8634146341463415

In [ ]:
predictions

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
model2 = RandomForestRegressor()

In [ ]:
model2.fit(x,y)

In [ ]:
predictons = model2.predict(x_test)

In [ ]:
predictions

In [ ]:
from sklearn.metrics import r2_score
y_pred = model2.predict(x_test)

In [ ]:
r2_score(y_test, y_pred)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [ ]:
print("CR:",classification_report(y_test,y_pred))
print('Confusion Matrix:\n\n',confusion_matrix(y_test,y_pred))
print('\nAccuracy Score :',accuracy_score(y_test,y_pred))